export const styles = {
  grow: {
    transformOrigin: "left bottom",
  },
  hide: {
    display: "none",
  },
  chat: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    position: "absolute",
    left: "20px",
    bottom: "64px",
    bgcolor: "primary.light",
    height: "600px",
    width: "450px",
    paddingButtom: "10%",
    boxShadow: 4,
    borderRadius: "12px",
    overflow: "auto",
  },
  chatHeader: {
    height: "15%",
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    bgcolor: "primary.dark",
    borderRadius: "12px 12px 0 0",
  },
  chatTitle: {
    color: "secondary.light",
  },
  messageContainer: {
    height: "75%",
    width: "100%",
    bgcolor: "#F5F4FC",
    overflowY: "scroll",
  },
  typeContainer: {
    width: "100%",
    bgcolor: "primary.light",
    borderWidth: "10px",
    borderTop: "2px solid #fcfcfc",
    borderRadius: "0 0 12px 12px",
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "end",
    flexWrap: "wrap",
    flex: 1,
  },
  typeField: {
    height: "100%",
    width: "80%",
    borderColor: "#fff",
    display: "flex",
    "&:hover": {
      borderColor: "#fff",
    },
  },
  input: {
    height: "100%",
  },
  sendButton: {
    width: "15%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
    borderLeft: "2px solid #fcfcfc",
  },
};
