#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "running pre commit hook"
cd frontend && npm run lint --fix && npm run prettier:fix
echo "please fix lint warnings/error and check if there is any uncommited files, then commit the changes again"
