#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

printf "Running pre commit hook\n"
cd frontend && npm run lint --fix && npm run prettier:fix
printf "\nPlease fix lint warnings/error in the frontend and check if there are any uncommited files, then commit the changes again\n"
